baseurl: "/catalog-api"
apiname: "API's Zaak-catalogus"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Zaak catalogus
    subnav:
      - title: Home
        path: /
#      - title: Productvisie
#        path: /productvisie/
#      - title: Standaard
#        path: /standaard/
#      - title: Ontwikkelaars
#        path: /ontwikkelaars/
#      - title: Thema's
#        path: /themas/
#      - title: Beheer
#        path: /beheer/
#      - title: Doorontwikkeling
#        path: /doorontwikkeling/
#      - title: Contact
#        path: /contact/

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: melsk-r/jekyll-theme-vng-realisatie

github: melsk-r/catalog-api

theme: jekyll-theme-time-machine

project_name: /gemma-zaken

standard_family: ZGW
